channels:
  - conda-forge
  - nodefaults
dependencies:
  - esmpy=8.4.*=mpi_mpich*
  - mpi4py=4.*
  - netcdf4=1.6.*=mpi_mpich*
  - pydantic=2.*
  - pydantic-settings
  - pyremap=2.1.*
  - python=3.11.*
