name: ufs-land-da-workflow
channels:
  - conda-forge
  - ufs-community
  - nodefaults
dependencies:
  - cartopy
  - f90nml
  - jcb
  - jinja2
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - pyyaml
  - scipy
  - uwtools
  - xarray
