name: ufs-land-da-wflow
channels:
  - conda-forge
  - ufs-community
  - nodefaults
dependencies:
  - cartopy
  - f90nml
  - jinja2
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - pyyaml
  - scipy
  - uwtools
  - xarray
  - pip:
    - git+https://github.com/NOAA-EMC/jcb.git@develop
